// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sum struct {
	Number1              int32    `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              int32    `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sum) Reset()         { *m = Sum{} }
func (m *Sum) String() string { return proto.CompactTextString(m) }
func (*Sum) ProtoMessage()    {}
func (*Sum) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{0}
}

func (m *Sum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sum.Unmarshal(m, b)
}
func (m *Sum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sum.Marshal(b, m, deterministic)
}
func (m *Sum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sum.Merge(m, src)
}
func (m *Sum) XXX_Size() int {
	return xxx_messageInfo_Sum.Size(m)
}
func (m *Sum) XXX_DiscardUnknown() {
	xxx_messageInfo_Sum.DiscardUnknown(m)
}

var xxx_messageInfo_Sum proto.InternalMessageInfo

func (m *Sum) GetNumber1() int32 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *Sum) GetNumber2() int32 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type CalculatorRequest struct {
	Sum                  *Sum     `protobuf:"bytes,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorRequest) Reset()         { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()    {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{1}
}

func (m *CalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorRequest.Unmarshal(m, b)
}
func (m *CalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorRequest.Merge(m, src)
}
func (m *CalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorRequest.Size(m)
}
func (m *CalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorRequest proto.InternalMessageInfo

func (m *CalculatorRequest) GetSum() *Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

type CalculatorResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorResponse) Reset()         { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()    {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{2}
}

func (m *CalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorResponse.Unmarshal(m, b)
}
func (m *CalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorResponse.Merge(m, src)
}
func (m *CalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorResponse.Size(m)
}
func (m *CalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorResponse proto.InternalMessageInfo

func (m *CalculatorResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//Prime API messages
type PrimeNumberRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberRequest) Reset()         { *m = PrimeNumberRequest{} }
func (m *PrimeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberRequest) ProtoMessage()    {}
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{3}
}

func (m *PrimeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberRequest.Unmarshal(m, b)
}
func (m *PrimeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberRequest.Merge(m, src)
}
func (m *PrimeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberRequest.Size(m)
}
func (m *PrimeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberRequest proto.InternalMessageInfo

func (m *PrimeNumberRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberResponse) Reset()         { *m = PrimeNumberResponse{} }
func (m *PrimeNumberResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberResponse) ProtoMessage()    {}
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{4}
}

func (m *PrimeNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberResponse.Unmarshal(m, b)
}
func (m *PrimeNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberResponse.Merge(m, src)
}
func (m *PrimeNumberResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberResponse.Size(m)
}
func (m *PrimeNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberResponse proto.InternalMessageInfo

func (m *PrimeNumberResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// Greatest Common Factor messages
type GCFRequest struct {
	Number1              int32    `protobuf:"varint,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              int32    `protobuf:"varint,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCFRequest) Reset()         { *m = GCFRequest{} }
func (m *GCFRequest) String() string { return proto.CompactTextString(m) }
func (*GCFRequest) ProtoMessage()    {}
func (*GCFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{5}
}

func (m *GCFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCFRequest.Unmarshal(m, b)
}
func (m *GCFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCFRequest.Marshal(b, m, deterministic)
}
func (m *GCFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCFRequest.Merge(m, src)
}
func (m *GCFRequest) XXX_Size() int {
	return xxx_messageInfo_GCFRequest.Size(m)
}
func (m *GCFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GCFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GCFRequest proto.InternalMessageInfo

func (m *GCFRequest) GetNumber1() int32 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *GCFRequest) GetNumber2() int32 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type GCFResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCFResponse) Reset()         { *m = GCFResponse{} }
func (m *GCFResponse) String() string { return proto.CompactTextString(m) }
func (*GCFResponse) ProtoMessage()    {}
func (*GCFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{6}
}

func (m *GCFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCFResponse.Unmarshal(m, b)
}
func (m *GCFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCFResponse.Marshal(b, m, deterministic)
}
func (m *GCFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCFResponse.Merge(m, src)
}
func (m *GCFResponse) XXX_Size() int {
	return xxx_messageInfo_GCFResponse.Size(m)
}
func (m *GCFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GCFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GCFResponse proto.InternalMessageInfo

func (m *GCFResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type BreakWordRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakWordRequest) Reset()         { *m = BreakWordRequest{} }
func (m *BreakWordRequest) String() string { return proto.CompactTextString(m) }
func (*BreakWordRequest) ProtoMessage()    {}
func (*BreakWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{7}
}

func (m *BreakWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakWordRequest.Unmarshal(m, b)
}
func (m *BreakWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakWordRequest.Marshal(b, m, deterministic)
}
func (m *BreakWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakWordRequest.Merge(m, src)
}
func (m *BreakWordRequest) XXX_Size() int {
	return xxx_messageInfo_BreakWordRequest.Size(m)
}
func (m *BreakWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BreakWordRequest proto.InternalMessageInfo

func (m *BreakWordRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type BreakWordResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreakWordResponse) Reset()         { *m = BreakWordResponse{} }
func (m *BreakWordResponse) String() string { return proto.CompactTextString(m) }
func (*BreakWordResponse) ProtoMessage()    {}
func (*BreakWordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{8}
}

func (m *BreakWordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreakWordResponse.Unmarshal(m, b)
}
func (m *BreakWordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreakWordResponse.Marshal(b, m, deterministic)
}
func (m *BreakWordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreakWordResponse.Merge(m, src)
}
func (m *BreakWordResponse) XXX_Size() int {
	return xxx_messageInfo_BreakWordResponse.Size(m)
}
func (m *BreakWordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BreakWordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BreakWordResponse proto.InternalMessageInfo

func (m *BreakWordResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// Letters messages
type LettersRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LettersRequest) Reset()         { *m = LettersRequest{} }
func (m *LettersRequest) String() string { return proto.CompactTextString(m) }
func (*LettersRequest) ProtoMessage()    {}
func (*LettersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{9}
}

func (m *LettersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LettersRequest.Unmarshal(m, b)
}
func (m *LettersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LettersRequest.Marshal(b, m, deterministic)
}
func (m *LettersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LettersRequest.Merge(m, src)
}
func (m *LettersRequest) XXX_Size() int {
	return xxx_messageInfo_LettersRequest.Size(m)
}
func (m *LettersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LettersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LettersRequest proto.InternalMessageInfo

func (m *LettersRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type LettersResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LettersResponse) Reset()         { *m = LettersResponse{} }
func (m *LettersResponse) String() string { return proto.CompactTextString(m) }
func (*LettersResponse) ProtoMessage()    {}
func (*LettersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{10}
}

func (m *LettersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LettersResponse.Unmarshal(m, b)
}
func (m *LettersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LettersResponse.Marshal(b, m, deterministic)
}
func (m *LettersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LettersResponse.Merge(m, src)
}
func (m *LettersResponse) XXX_Size() int {
	return xxx_messageInfo_LettersResponse.Size(m)
}
func (m *LettersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LettersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LettersResponse proto.InternalMessageInfo

func (m *LettersResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Sum)(nil), "calculator.Sum")
	proto.RegisterType((*CalculatorRequest)(nil), "calculator.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "calculator.CalculatorResponse")
	proto.RegisterType((*PrimeNumberRequest)(nil), "calculator.PrimeNumberRequest")
	proto.RegisterType((*PrimeNumberResponse)(nil), "calculator.PrimeNumberResponse")
	proto.RegisterType((*GCFRequest)(nil), "calculator.GCFRequest")
	proto.RegisterType((*GCFResponse)(nil), "calculator.GCFResponse")
	proto.RegisterType((*BreakWordRequest)(nil), "calculator.BreakWordRequest")
	proto.RegisterType((*BreakWordResponse)(nil), "calculator.BreakWordResponse")
	proto.RegisterType((*LettersRequest)(nil), "calculator.LettersRequest")
	proto.RegisterType((*LettersResponse)(nil), "calculator.LettersResponse")
}

func init() {
	proto.RegisterFile("calculatorpb/calculator.proto", fileDescriptor_87e717c78a24322a)
}

var fileDescriptor_87e717c78a24322a = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4b, 0x4f, 0xfa, 0x40,
	0x14, 0xc5, 0xff, 0xfc, 0xab, 0x10, 0x0e, 0x06, 0xe4, 0x9a, 0x20, 0xa9, 0xe2, 0xa3, 0x51, 0xa3,
	0x51, 0x51, 0x6b, 0x62, 0xa2, 0x2b, 0x03, 0x09, 0x6c, 0xd0, 0x98, 0xb2, 0x30, 0x71, 0xc7, 0x63,
	0x16, 0x44, 0x4a, 0x71, 0xda, 0xd1, 0xaf, 0xe0, 0xc7, 0x36, 0x14, 0xda, 0xb9, 0xc8, 0x2b, 0x71,
	0xd7, 0x3b, 0xe7, 0xcc, 0xef, 0x34, 0xf7, 0x64, 0x50, 0xea, 0xb4, 0xfa, 0x1d, 0xd5, 0x6f, 0x05,
	0x9e, 0x1c, 0xb6, 0xaf, 0xf4, 0x50, 0x1e, 0x4a, 0x2f, 0xf0, 0x08, 0xfa, 0xc4, 0xba, 0x87, 0xd1,
	0x54, 0x2e, 0x15, 0x91, 0x1a, 0x28, 0xb7, 0x2d, 0xe4, 0x4d, 0x31, 0x71, 0x90, 0x38, 0x5d, 0x77,
	0xa2, 0x51, 0x2b, 0x76, 0xf1, 0x3f, 0x57, 0x6c, 0xeb, 0x0e, 0xf9, 0x6a, 0x0c, 0x72, 0xc4, 0x87,
	0x12, 0x7e, 0x40, 0x87, 0x30, 0x7c, 0xe5, 0x86, 0x90, 0x8c, 0x9d, 0x2b, 0xb3, 0xec, 0xa6, 0x72,
	0x9d, 0x91, 0x66, 0x5d, 0x80, 0xf8, 0x3d, 0x7f, 0xe8, 0x0d, 0x7c, 0x41, 0x05, 0x24, 0xa5, 0xf0,
	0x55, 0x3f, 0x98, 0xfc, 0xc0, 0x64, 0x1a, 0xb9, 0x5f, 0x64, 0xcf, 0x15, 0xcf, 0x61, 0x6a, 0x14,
	0x53, 0x40, 0x72, 0xfc, 0x1b, 0x91, 0x7b, 0x3c, 0x59, 0x97, 0xd8, 0x9a, 0x72, 0xaf, 0x80, 0x3f,
	0x02, 0xf5, 0x6a, 0x2d, 0x82, 0xfe, 0x65, 0x09, 0xc7, 0xc8, 0x84, 0x84, 0x15, 0x41, 0x27, 0xd8,
	0xac, 0x48, 0xd1, 0x7a, 0x7f, 0xf5, 0x64, 0x37, 0x8a, 0x23, 0xac, 0x7d, 0x79, 0xb2, 0x1b, 0x3a,
	0xd3, 0x4e, 0xf8, 0x6d, 0x9d, 0x23, 0xcf, 0x7c, 0x73, 0xa1, 0xe9, 0x18, 0x7a, 0x84, 0x6c, 0x43,
	0x04, 0x81, 0x90, 0xfe, 0x32, 0xe4, 0x19, 0x72, 0xb1, 0x6b, 0x39, 0xd0, 0xfe, 0x36, 0x78, 0xa5,
	0x4d, 0x21, 0x3f, 0x7b, 0x1d, 0x41, 0x4f, 0x80, 0x3e, 0xa4, 0x12, 0xef, 0x74, 0xa6, 0x7f, 0x73,
	0x6f, 0x91, 0x3c, 0x8e, 0xb6, 0xfe, 0x91, 0x83, 0x0c, 0xab, 0x88, 0xa6, 0x2e, 0xcc, 0x36, 0x6d,
	0xee, 0x2f, 0xd4, 0x23, 0xe2, 0x75, 0x82, 0x1e, 0x60, 0xd4, 0xab, 0x35, 0x2a, 0x70, 0xaf, 0x2e,
	0xd6, 0xdc, 0x9e, 0x39, 0x67, 0x77, 0x1b, 0x48, 0xc7, 0x2b, 0xa7, 0x5d, 0xee, 0xfc, 0xdd, 0x98,
	0x59, 0x5a, 0xa0, 0x32, 0x5a, 0x0d, 0xa9, 0xc9, 0xb6, 0xc9, 0xe4, 0xee, 0xe9, 0xa2, 0xcc, 0x9d,
	0xb9, 0x9a, 0xe6, 0x54, 0xb2, 0x6f, 0x1b, 0xfc, 0x11, 0xb7, 0x93, 0xe1, 0xd3, 0xbd, 0xfd, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x5d, 0xb4, 0x16, 0xdb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	// Calculator Takes in two numbers and returns the sum of them
	Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	// PrimeNUmberDecomposition rpc
	PrimeNumber(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberClient, error)
	// Get the GCF(Greatest Common Factor) of 2 numbers
	GCF(ctx context.Context, in *GCFRequest, opts ...grpc.CallOption) (CalculatorService_GCFClient, error)
	// break a sentance appart into words
	BreakWord(ctx context.Context, in *BreakWordRequest, opts ...grpc.CallOption) (CalculatorService_BreakWordClient, error)
	// letters
	Letters(ctx context.Context, in *LettersRequest, opts ...grpc.CallOption) (CalculatorService_LettersClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumber(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumber", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) GCF(ctx context.Context, in *GCFRequest, opts ...grpc.CallOption) (CalculatorService_GCFClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[1], "/calculator.CalculatorService/GCF", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceGCFClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_GCFClient interface {
	Recv() (*GCFResponse, error)
	grpc.ClientStream
}

type calculatorServiceGCFClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceGCFClient) Recv() (*GCFResponse, error) {
	m := new(GCFResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) BreakWord(ctx context.Context, in *BreakWordRequest, opts ...grpc.CallOption) (CalculatorService_BreakWordClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[2], "/calculator.CalculatorService/BreakWord", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceBreakWordClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_BreakWordClient interface {
	Recv() (*BreakWordResponse, error)
	grpc.ClientStream
}

type calculatorServiceBreakWordClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceBreakWordClient) Recv() (*BreakWordResponse, error) {
	m := new(BreakWordResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) Letters(ctx context.Context, in *LettersRequest, opts ...grpc.CallOption) (CalculatorService_LettersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[3], "/calculator.CalculatorService/Letters", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceLettersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_LettersClient interface {
	Recv() (*LettersResponse, error)
	grpc.ClientStream
}

type calculatorServiceLettersClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceLettersClient) Recv() (*LettersResponse, error) {
	m := new(LettersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	// Calculator Takes in two numbers and returns the sum of them
	Calculator(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	// PrimeNUmberDecomposition rpc
	PrimeNumber(*PrimeNumberRequest, CalculatorService_PrimeNumberServer) error
	// Get the GCF(Greatest Common Factor) of 2 numbers
	GCF(*GCFRequest, CalculatorService_GCFServer) error
	// break a sentance appart into words
	BreakWord(*BreakWordRequest, CalculatorService_BreakWordServer) error
	// letters
	Letters(*LettersRequest, CalculatorService_LettersServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Calculator(ctx context.Context, req *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculator not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumber(req *PrimeNumberRequest, srv CalculatorService_PrimeNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumber not implemented")
}
func (*UnimplementedCalculatorServiceServer) GCF(req *GCFRequest, srv CalculatorService_GCFServer) error {
	return status.Errorf(codes.Unimplemented, "method GCF not implemented")
}
func (*UnimplementedCalculatorServiceServer) BreakWord(req *BreakWordRequest, srv CalculatorService_BreakWordServer) error {
	return status.Errorf(codes.Unimplemented, "method BreakWord not implemented")
}
func (*UnimplementedCalculatorServiceServer) Letters(req *LettersRequest, srv CalculatorService_LettersServer) error {
	return status.Errorf(codes.Unimplemented, "method Letters not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Calculator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculator(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumber(m, &calculatorServicePrimeNumberServer{stream})
}

type CalculatorService_PrimeNumberServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_GCF_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GCFRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).GCF(m, &calculatorServiceGCFServer{stream})
}

type CalculatorService_GCFServer interface {
	Send(*GCFResponse) error
	grpc.ServerStream
}

type calculatorServiceGCFServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceGCFServer) Send(m *GCFResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_BreakWord_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BreakWordRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).BreakWord(m, &calculatorServiceBreakWordServer{stream})
}

type CalculatorService_BreakWordServer interface {
	Send(*BreakWordResponse) error
	grpc.ServerStream
}

type calculatorServiceBreakWordServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceBreakWordServer) Send(m *BreakWordResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_Letters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LettersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).Letters(m, &calculatorServiceLettersServer{stream})
}

type CalculatorService_LettersServer interface {
	Send(*LettersResponse) error
	grpc.ServerStream
}

type calculatorServiceLettersServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceLettersServer) Send(m *LettersResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculator",
			Handler:    _CalculatorService_Calculator_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumber",
			Handler:       _CalculatorService_PrimeNumber_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GCF",
			Handler:       _CalculatorService_GCF_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BreakWord",
			Handler:       _CalculatorService_BreakWord_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Letters",
			Handler:       _CalculatorService_Letters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculatorpb/calculator.proto",
}
